### ISSUE TITLE
Setup Push Notifications for Android

### ISSUE THREAD

**Issue by isupeene** [isupeene/small_jobs#3]
Research Google Cloud Messaging and enable push notifications in our app.

**Comment by msabbasi** [comment]
@isupeene I'm not getting any notifications from the server. I tested my side from a demo server and I'm getting notifications from there.

**Comment by isupeene** [comment]
What demo server?

**Comment by msabbasi** [comment]
I used http://gcm-alert.appspot.com/

**Comment by msabbasi** [comment]
I have sent you a new API key. I am now using curl to test it.

**Comment by isupeene** [comment]
So is this working now?

**Comment by msabbasi** [comment]
It's not. I don't understand why.

**Comment by isupeene** [comment]
You're testing deleting / modifying postings via the job posting app, not
the admin app, right?

~Isaac

2015-03-25 11:08 GMT-06:00 msabbasi <notifications@github.com>:

**Comment by msabbasi** [comment]
Oh wait. I'll try something I just thought of and I'll get back to you as soon as possible.

**Comment by msabbasi** [comment]
Yeap, that's what I just realized.

**Comment by msabbasi** [comment]
Sorry!

**Comment by msabbasi** [comment]
It's working!

**Comment by isupeene** [comment]
Awesome!

~Isaac

2015-03-25 12:21 GMT-06:00 msabbasi <notifications@github.com>:

**Comment by isupeene** [comment]
Resolved by #24
