### ISSUE TITLE
Input validation in forms

### ISSUE THREAD

**Issue by vzphung** [isupeene/small_jobs#38]
Probably validate through JavaScript before submitting. Take a peek at Isaacs checks.

**Comment by isupeene** [comment]
I know the admin form does it automatically from the model validators - you could probably do something similar to avoid writing a lot of duplicate validators.

**Comment by vzphung** [comment]
Should be good. I just print out the errors on the webpage.

**Comment by vzphung** [comment]
Init use of model forms in #53
