### ISSUE TITLE
Enable contractors to edit their profiles

### ISSUE THREAD

**Issue by msabbasi** [isupeene/small_jobs#48]
@isupeene Is there a way to do this right now?

**Comment by isupeene** [comment]
Not yet - I can add one tomorrow.

**Comment by msabbasi** [comment]
Okay, thank you!

**Comment by msabbasi** [comment]
@isupeene When I try to update a profile, it gives me the error, "Email: This field must be unique."

**Comment by msabbasi** [comment]
@isupeene When I try to update a profile, it gives me the error, "Email: This field must be unique."

**Comment by msabbasi** [comment]
Resolved by #60
